name: Vercel Server Preview Deployment

env: 
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID_SERVER }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_SERVER }}

on:
  push:
    branches-ignore:
      - main
    paths:
      - 'server/**'

jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install --global vercel

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
